name: Build and Test on Linux

on: [push]

jobs:
  Linux:

    runs-on: ubuntu-20.04

    steps:
    - name: Install Packages
      run: sudo apt-get install zlib1g-dev make libopenmpi-dev picosat

    - uses: actions/checkout@v1

    - name: submodules
      run: git submodule update --init --recursive

    - name: hordesat build
      run: make -C hordesat-src -j $(nproc)

    - name: run CI script
      env:
        RUNFUZZ: 1
      run: ./tools/ci.sh

